# Generated by Django 4.1.2 on 2023-06-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=10)),
                ('cat', models.CharField(max_length=50)),
                ('num_staff_allocated', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
