# Generated by Django 4.1.2 on 2023-06-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
                ('probation_year', models.CharField(max_length=10)),
                ('annual_availability', models.IntegerField()),
                ('unadjusted_max', models.IntegerField()),
                ('adjusted_max', models.IntegerField()),
                ('availability_notes', models.TextField()),
                ('employment_end_date', models.DateField()),
                ('probation_start_date', models.DateField()),
                ('probation_start_year_stage', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_staff',
            },
        ),
    ]
