# Generated by Django 4.1.2 on 2023-06-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_admin_role',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_project',
            },
        ),
        migrations.CreateModel(
            name='StaffRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('teach_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('admin_role_jd', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_staff_relaction',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach',
            },
        ),
    ]
