# Generated by Django 4.1.2 on 2023-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffvModules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('linked_courses', models.CharField(max_length=100)),
                ('unlinked_relatives', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('num_staff_allocated', models.IntegerField()),
                ('est_num_students', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_course',
            },
        ),
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('crit', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_school_role',
            },
        ),
        migrations.CreateModel(
            name='TeachAdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach_admin_role',
            },
        ),
        migrations.CreateModel(
            name='TeachCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach_course',
            },
        ),
        migrations.CreateModel(
            name='TeachProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach_project',
            },
        ),
        migrations.CreateModel(
            name='TeachSchoolRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach_school_role',
            },
        ),
        migrations.CreateModel(
            name='TeachUniRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('alpha', models.CharField(max_length=100)),
                ('beta', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('delta', models.CharField(max_length=100)),
                ('share', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('total_hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_teach_uni_role',
            },
        ),
        migrations.CreateModel(
            name='UniRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('crit', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'balancer_uni_role',
            },
        ),
        migrations.DeleteModel(
            name='StaffRelation',
        ),
        migrations.DeleteModel(
            name='Teach',
        ),
        migrations.RenameField(
            model_name='adminrole',
            old_name='credits',
            new_name='crit',
        ),
        migrations.RenameField(
            model_name='adminrole',
            old_name='num_students',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='adminrole',
            old_name='alpha',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='adminrole',
            old_name='total_hours',
            new_name='num_staff_allocated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='alpha',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='credits',
            new_name='est_num_students',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='num_students',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='beta',
            new_name='linked_courses',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='coordinator',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_hours',
            new_name='num_staff_allocated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='delta',
            new_name='unlinked_relatives',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='share',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='share',
        ),
    ]
