# Generated by Django 4.1.2 on 2023-06-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffvModules', '0003_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
