# Generated by Django 4.1.2 on 2023-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffvModules', '0004_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
