# Generated by Django 4.1.2 on 2023-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffvModules', '0005_course_hs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachadminrole',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachcourse',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachproject',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachschoolroles',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachuniroles',
            name='total_hours',
            field=models.CharField(max_length=100),
        ),
    ]
